[manifest]
id = "slow_shoe"
version = "1.0.0"
display_name = "Slow Shoe"
description = "Slows down the toes sequence in K Rool"
short_description = "Slows down the toes sequence in K Rool"
authors = [ "Ballaam" ]
game_id = "dk64"
minimum_recomp_version = "1.0.2"

[inputs]
elf_path = "build/mod.elf"
mod_filename = "slow_shoe"
func_reference_syms_file = "Dk64Syms/dump.toml"
data_reference_syms_files = [ "Dk64Syms/data_dump.toml" ]
additional_files = ["thumb.dds"]
